### PR TITLE
Add support for `formatDuration` and `formatDurationToParts`

### PR DESCRIPTION
**Pull request by Ephys**
This issue adds support for two new API methods and resolves issue #4 

It adds 
- `formatDuration(intl, seconds, opts = { format }): string` which outputs the formatted duration as a string.
- `formatDurationToParts(intl, seconds, opts = { format }): Array<{ type, value }>` which outputs the formatted duration as an array of token similar to what [DateTimeFormat#formatToParts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts) produces.

Couple things I'd like to point out:
- I had to rewrite most of the internal code to remove any dependency on react. `DurationMessage` is instead a thin layer on top of `formatDurationToParts`. There are however no new breaking change.
- I tried to keep the lib as aligned with `react-intl` (and native `Intl`) as possible except for some points I'd like to fix:
  - `DurationMessage` hasn't been renamed to `FormattedDuration` (out of scope -- separate PR, breaking change).
  - `formatDurationToParts` produces tokens of type `seconds`, `minutes`, `hours`, etc. But the native `formatToParts` produces the types `second`, `minute`, `hour`, etc.
    Fixing this would require either special-casing (😟) or changing the variables names in `messages.js` (breaking change).
  - Add support for `<DurationMessage>{(data) => printDuration(data)}</DurationMessage>` (out of scope -- separate PR)
- [DurationMessage copies a prototype method from FormattedNumber](https://github.com/en-japan-air/react-intl-formatted-duration/compare/master...Ephys:master#diff-337d93fdda41d43a61b559b8182b4319R49). This is because we need access to an [internal method from `react-intl`](https://github.com/yahoo/react-intl/blob/master/src/utils.js#L83) which would be expensive to re-implement. This should be changed as soon as possible. The best solution would be to ask `react-intl` to expose and support that internal method (or similar).
- I had to implement a method to format a message as a list of tokens (to be able to wrap the variables). `react-intl` has a [very similar method](https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L58) they use to inject react components. Long term such a method should be proposed to [`intl-messageformat`](https://github.com/yahoo/intl-messageformat) which handles that formatting.
- I might have done too many tests.

### CODE REVIEW

**Comment by piuccio** [comment]
wow I thought it would be easier to do! I need some time to go over it.

Just a couple comments on your message, I didn't read any code yet:

> formatDurationToParts

Is it clever (or maybe stupid) enough to output tokens based on the format?

`formatDurationToParts(intl, 90, { format: '{seconds}' })` should return `[{ type: 'second', value: 90 }]`
`formatDurationToParts(intl, 90, { format: '{minutes} {seconds}' })` should return `[{ type: 'minute' value: 1 }, { type: 'second', value: 30 }]`

> DurationMessage hasn't been renamed to FormattedDuration

we can always export both, no breaking change. However I didn't call it `FormattedDuration` in the first place because I thought `react-intl` would eventually implement it, most likely with a different API so I didn't want to create confusion in the future

> formatDurationToParts produces tokens of type seconds, minutes, hours

like before, how bad is it if we generate both `second` and `seconds`? Btw I'm not too much against a breaking change, this package is downloaded < 600 times per week on npm, it won't annoy too many people.

> DurationMessage copies a prototype method from FormattedNumber

This one bothers me most. Being dependent on internal methods is always dangerous. They can change the internals without notice or major version updates and this package would stop working. Basically we throw semver out of the window. Would you mind opening an issue on their repo to expose the needed API?

> I might have done too many tests.

As long as you test the public interface too many tests is never a problem


One last point, very biased to my use case and the whole reason why I created this project in the first place

```
<FormattedDuration seconds={65} textComponent={Text} valueComponent={Value} />
```

generates

```
<Text><Value>1</Value> minute <Value>5</Value> seconds</Text>
```

I need a way to wrap numbers in another component, which is probably what you mean by `I had to implement a method to format a message as a list of tokens`. If this use case works, I'm happy with the changes

**Comment by Ephys** [comment]
> Is it clever (or maybe stupid) enough to output tokens based on the format?

That's what it should do, but not exactly what your example returned. It won't just return the number tokens but the text between the numbers too.

```js
// i.e. where
formatDuration(intl, 90, { format: '{minutes} {seconds}' }) 
// returns '1 30'

formatDurationToParts(intl, 90, { format: '{minutes} {seconds}' }) 
// returns 
// [
//   { type: 'minutes', value: '1' },
//   { type: 'literal', value: ' ' },
//   { type: 'seconds', value: '30' },
// ]
```

[Some examples here](https://github.com/en-japan-air/react-intl-formatted-duration/pull/8/files#diff-0f0ae38166425f76cc7714cae35e07e4R170)

> I didn't call it FormattedDuration in the first place because I thought react-intl would eventually implement it

I assumed so. I think that's wise and we should keep `DurationMessage` then

> how bad is it if we generate both second and seconds

Sadly we can't, tokens only have one type :(
Unless you mean how bad is it if we differ from `DateTimeFormat`? Not much I just like consistency and it's very likely that the future native `Intl.DurationFormat` will align its token types with `DateTimeFormat`'s

> I'm not too much against a breaking change

If it's alright with you to change the variable names in the messages, I'll get to it

> Being dependent on internal methods is always dangerous

Definitely agree. I'll open an issue on their repository. Should I just duplicate the internal method until `react-intl` makes the change? It's heavier but safer and should be temporary.

> `<FormattedDuration seconds={65} textComponent={Text} valueComponent={Value} />`
> generates
> `<Text><Value>1</Value> minute <Value>5</Value> seconds</Text>`

That part should not have changed unless I made a mistake. I'll add tests to make sure the component generates the same markup as before

**Comment by Ephys** [comment]
Related issue: https://github.com/yahoo/react-intl/issues/1099

**Comment by piuccio** [comment]
I tried to split the PR in smaller chunks, #10 is the first attempt

**Comment by piuccio** [comment]
Sorry if it took forever to get any progress on this, I've merged #15 which uses an external library to format tokens to parts. I'll release it as `3.0.0`

**Pull request closed without merging**
